services:
    # Twig extension
    admin.twig.extension:
        class: Puzzle\Admin\AdminBundle\Twig\AdminExtension
        arguments: [ '@doctrine.orm.entity_manager', "@twig", '%puzzle_admin%' ]
        tags:
            - { name: twig.extension }